#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
export PATH="/opt/homebrew/bin:$PATH"

# 1) Validate committer email

EMAIL=$(git config user.email)


# 2) Lint staged files

pnpm exec lint-staged
